"""tools.report — the shared CSV/JSON/markdown writers.

Pure functions over data. The run date is injected rather than read from the
clock so a report is reproducible and these tests are not time-dependent.
"""

from __future__ import annotations

import json

from tools import report


def test_write_csv_uses_the_given_column_order(tmp_path):
    out = tmp_path / "rows.csv"
    report.write_csv(out, [{"b": 2, "a": 1}], columns=("a", "b"))
    assert out.read_text().splitlines()[0] == "a,b"


def test_write_csv_writes_row_values(tmp_path):
    out = tmp_path / "rows.csv"
    report.write_csv(out, [{"a": 1, "b": "x"}, {"a": 2, "b": "y"}], columns=("a", "b"))
    assert out.read_text().splitlines()[1:] == ["1,x", "2,y"]


def test_write_csv_creates_missing_parent_directories(tmp_path):
    out = tmp_path / "deep" / "nested" / "rows.csv"
    report.write_csv(out, [{"a": 1}], columns=("a",))
    assert out.exists()


def test_write_json_sorts_keys_so_reruns_are_byte_identical(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    report.write_json(a, {"z": 1, "a": {"n": 2, "m": 3}})
    report.write_json(b, {"a": {"m": 3, "n": 2}, "z": 1})
    assert a.read_bytes() == b.read_bytes()


def test_write_json_round_trips(tmp_path):
    out = tmp_path / "s.json"
    payload = {"total": 1307, "by_brand": {"VOCO": 292}}
    report.write_json(out, payload)
    assert json.loads(out.read_text()) == payload


def test_table_renders_a_github_markdown_table():
    md = report.table(["brand", "pdfs"], [["VOCO", 292], ["GC", 149]])
    assert md.splitlines() == [
        "| brand | pdfs |",
        "|---|---|",
        "| VOCO | 292 |",
        "| GC | 149 |",
    ]


def test_table_escapes_pipes_in_values():
    """Verbatim document text can contain a pipe and would break the table."""
    md = report.table(["v"], [["a|b"]])
    assert "a\\|b" in md


def test_table_with_no_rows_still_renders_a_header():
    md = report.table(["a"], [])
    assert md.splitlines() == ["| a |", "|---|"]


def test_write_markdown_composes_title_date_and_sections_in_order(tmp_path):
    out = tmp_path / "r.md"
    report.write_markdown(
        out,
        title="Corpus analysis",
        date="2026-07-24",
        intro="Generated by `python -m tools corpus`.",
        sections=[("First", "one"), ("Second", "two")],
    )
    text = out.read_text()
    assert text.startswith("# Corpus analysis\n")
    assert "2026-07-24" in text
    assert "Generated by `python -m tools corpus`." in text
    assert text.index("## First") < text.index("## Second")


def test_write_markdown_is_deterministic_for_the_same_inputs(tmp_path):
    kwargs = dict(title="T", date="2026-07-24", intro="i", sections=[("S", "b")])
    report.write_markdown(tmp_path / "a.md", **kwargs)
    report.write_markdown(tmp_path / "b.md", **kwargs)
    assert (tmp_path / "a.md").read_bytes() == (tmp_path / "b.md").read_bytes()
