"""CLI dispatch for the analysis tooling.

    python -m tools corpus [--root DIR] [--out DIR] [--date YYYY-MM-DD]

Thin on purpose: argument parsing and file naming only. The measuring lives in
the analyzer modules, the writing in `tools.report`. Later chunks add the
`catalogue`, `crossref` and `claims` subcommands here.
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import sys

from tools import catalogue, claims, corpus, crossref, report

DEFAULT_CORPUS_ROOT = "imports/dentalia-sftp"
DEFAULT_OUT = "analysis-out"


def _cmd_corpus(args) -> int:
    root = pathlib.Path(args.root)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2

    rows = corpus.scan(root)
    if not rows:
        print(f"error: no PDFs found under {root}", file=sys.stderr)
        return 2

    summary = corpus.aggregate(rows)
    support = corpus.support_files(root)
    stem = pathlib.Path(args.out) / f"corpus-{args.date}"

    report.write_csv(stem.with_suffix(".csv"), rows, columns=corpus.COLUMNS)
    report.write_json(stem.with_suffix(".json"), summary)
    report.write_markdown(
        stem.with_suffix(".md"),
        title=f"Corpus analysis — {root}",
        date=args.date,
        intro=f"Generated by `python -m tools corpus --root {root}`. T0 only, no LLM, no database.",
        sections=corpus.render(summary, support),
    )

    print(
        f"{summary['total_pdfs']} PDFs · {summary['scanned']} scanned · "
        f"{summary['extraction_eligible']} eligible · "
        f"{summary['t0_fully_missed']} with no T0 field · "
        f"{summary['errors']} unreadable"
    )
    print(f"wrote {stem}.csv/.json/.md")
    return 0


def _cmd_claims(args) -> int:
    root = pathlib.Path(args.root)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2

    rows = corpus.scan(root)
    if not rows:
        print(f"error: no PDFs found under {root}", file=sys.stderr)
        return 2

    summary = corpus.aggregate(rows)
    support = corpus.support_files(root)
    checked = claims.check(summary, support=support)
    stem = pathlib.Path(args.out) / f"claims-{args.date}"

    report.write_csv(stem.with_suffix(".csv"), checked, columns=claims.ROW_COLUMNS)
    report.write_markdown(
        stem.with_suffix(".md"),
        title=f"Corpus claim check — {root}",
        date=args.date,
        intro=f"Documented numbers vs measured, via `python -m tools claims --root {root}`.",
        sections=claims.render(checked),
    )

    n = {v: sum(1 for r in checked if r["verdict"] == v) for v in ("match", "mismatch", "not-measured")}
    print(f"{n['match']} match · {n['mismatch']} mismatch · {n['not-measured']} not-measured")
    print(f"wrote {stem}.csv/.md")
    return 0


def _cmd_catalogue(args) -> int:
    export = pathlib.Path(args.export)
    if not export.is_file():
        print(f"error: {export} is not a file", file=sys.stderr)
        return 2

    rows, summary = catalogue.profile(str(export), catalogue=args.catalogue)
    stem = pathlib.Path(args.out) / f"catalogue-{args.date}"

    report.write_csv(stem.with_suffix(".csv"), rows, columns=catalogue.COLUMNS)
    report.write_markdown(
        stem.with_suffix(".md"),
        title=f"Catalogue profile — {export.name}",
        date=args.date,
        intro=f"Profiled via INGEST's own CsvExportAdapter (`python -m tools catalogue`). Read-only.",
        sections=catalogue.render(summary),
    )

    tri = summary["md_flag"]
    print(
        f"{summary['total_items']} items · MD {tri['true']} / non-MD {tri['false']} / "
        f"unknown {tri['unknown']} · {summary['distinct_codes']} codes · "
        f"missing_mfr_ref {summary['missing_mfr_ref']['pct']}%"
    )
    print(f"wrote {stem}.csv/.md")
    return 0


def _cmd_crossref(args) -> int:
    root = pathlib.Path(args.root)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2
    export = pathlib.Path(args.export)
    if not export.is_file():
        print(f"error: {export} is not a file", file=sys.stderr)
        return 2

    rows = crossref.sweep(str(root), str(export))
    stem = pathlib.Path(args.out) / f"crossref-{args.date}"

    report.write_csv(stem.with_suffix(".csv"), rows, columns=crossref.ROW_COLUMNS)
    report.write_markdown(
        stem.with_suffix(".md"),
        title="Manufacturer-code cross-reference (candidates)",
        date=args.date,
        intro="Reproduces the code sweep via tracker↔BC joins (`python -m tools crossref`). "
              "Candidate list only — never writes pipeline config.",
        sections=crossref.render(rows),
    )

    from collections import Counter
    tiers = Counter(r["tier"] or "none" for r in rows)
    print("tiers: " + " · ".join(f"{n} {t}" for t, n in sorted(tiers.items())))
    print(f"wrote {stem}.csv/.md")
    return 0


def _cmd_bc_api(args) -> int:
    """Gap check: does the published BC API carry everything INGEST needs?

    Prints to stdout only -- no file output, no DB, no network. `--out`/`--date`
    are accepted (inherited from the common parent) and ignored.
    """
    from . import bc_api

    bc_api.report()
    return 0


def main(argv: list[str] | None = None) -> int:
    # Common options live on a parent parser so they are accepted AFTER the
    # subcommand (`... corpus --out X`), which is where a user naturally types
    # them, and so later subcommands inherit them unchanged.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--out", default=DEFAULT_OUT, help=f"output directory (default: {DEFAULT_OUT})"
    )
    common.add_argument(
        "--date",
        default=datetime.date.today().isoformat(),
        help="date stamp for output filenames (default: today)",
    )

    parser = argparse.ArgumentParser(prog="python -m tools", description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser(
        "corpus", parents=[common], help="analyze a PDF corpus tree (T0, read-only)"
    )
    c.add_argument(
        "--root", default=DEFAULT_CORPUS_ROOT,
        help=f"corpus root (default: {DEFAULT_CORPUS_ROOT})",
    )
    c.set_defaults(func=_cmd_corpus)

    cl = sub.add_parser(
        "claims", parents=[common], help="check the analysis doc's numbers vs measured"
    )
    cl.add_argument(
        "--root", default=DEFAULT_CORPUS_ROOT,
        help=f"corpus root (default: {DEFAULT_CORPUS_ROOT})",
    )
    cl.set_defaults(func=_cmd_claims)

    ca = sub.add_parser(
        "catalogue", parents=[common], help="profile a BC export via CsvExportAdapter"
    )
    ca.add_argument("--export", required=True, help="path to a BC export (.xlsx / .csv)")
    ca.add_argument("--catalogue", default="LJ", help="catalogue tag (default: LJ)")
    ca.set_defaults(func=_cmd_catalogue)

    cr = sub.add_parser(
        "crossref", parents=[common], help="tracker x BC manufacturer-code candidates"
    )
    cr.add_argument(
        "--root", default=DEFAULT_CORPUS_ROOT,
        help=f"corpus root holding the tracker spreadsheets (default: {DEFAULT_CORPUS_ROOT})",
    )
    cr.add_argument("--export", required=True, help="path to a BC export (.xlsx / .csv)")
    cr.set_defaults(func=_cmd_crossref)

    ba = sub.add_parser(
        "bc-api", parents=[common],
        help="BC REST API sample vs the Excel exports vs item_mirror/vendor_master",
    )
    ba.set_defaults(func=_cmd_bc_api)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":                        # pragma: no cover
    raise SystemExit(main())
